In [2]:
import module01

five is executed


In [4]:
import module001

In [5]:
dir(module001)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'five',
 'four',
 'one',
 'three',
 'two',
 'z']

In [7]:
#z=filename,classname
z=module01.five()
z.a()

five is executed


In [8]:
import module02

In [9]:
from module02 import*

In [11]:
obj=C('python',55,100,'all')

In [12]:
obj.display3()

name python
age 55
rollno 100
branch all


In [13]:
import packageclass

In [ ]:
from packageclass import module01

In [14]:
from packageclass import module02

In [15]:
from packageclass import *

### Numpy
- numerical python
- scientific computing
- it is more faster than list
- it supports multidimensional data

In [17]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [19]:
n=np.array([1,2,3])
n

array([1, 2, 3])

In [46]:
a=np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
a.ndim  #returns the dimension of the given array

2

In [20]:
a.shape  #returns the no of rows and columns

(2, 3)

In [21]:
a.size   #returns total no of elememts present in the array

6

In [22]:
#arange
#arange(start,end,step)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a=np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a.ndim

1

In [27]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
np.arange(21,1,-2)

array([21, 19, 17, 15, 13, 11,  9,  7,  5,  3])

In [32]:
np.arange(1,21,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [34]:
np.arange(1,21,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [35]:
np.linspace(1,10,5)  #generating 5 values between 1-10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
np.linspace(1,10,7)   #including 10

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [37]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [38]:
np.linspace(1,10,4,endpoint=False)  #excludes 10 as endpoint=false

array([1.  , 3.25, 5.5 , 7.75])

In [39]:
np.linspace(1,10,4,endpoint=False,retstep=True)

(array([1.  , 3.25, 5.5 , 7.75]), 2.25)

In [40]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [41]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [42]:
np.array([1,2,3],dtype=str)

array(['1', '2', '3'], dtype='<U1')

In [43]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [51]:
np.empty([2,3],dtype=float)

array([[3.16202013e-322, 0.00000000e+000, 3.80364755e+175],
       [1.04908564e-042, 2.35908937e+184, 2.25568769e+180]])

In [50]:
np.empty([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
np.empty([2,3],dtype=complex)

array([[1.07998018e-311+3.16202013e-322j,
        0.00000000e+000+0.00000000e+000j,
        0.00000000e+000+3.80364755e+175j],
       [4.85123402e-033+1.04908564e-042j,
        4.03550164e+175+2.35908937e+184j,
        4.04828879e-037+2.25568769e+180j]])

In [52]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones([4,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
np.random.random()

0.1350677053340964

In [58]:
np.random.random()

0.5230824774263532

In [65]:
np.random.randint(1,10)

3

In [66]:
np.random.randint([1,10])

array([0, 7])