In [4]:
import numpy as np
n=np.arange(1,21).reshape(5,4)
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

### Indexing in numpy

In [5]:
n[0]

array([1, 2, 3, 4])

In [6]:
n[0][1]

2

In [8]:
n[-1][1]

18

In [9]:
n[3][2]

15

In [10]:
n[4]

array([17, 18, 19, 20])

In [11]:
# Slicing
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [16]:
#n[rows,columns]
n[0:3,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [17]:
n[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [25]:
n[3:,2:]

array([[15, 16],
       [19, 20]])

In [28]:
n[1:4:2,1:4:2]

array([[ 6,  8],
       [14, 16]])

In [29]:
n[1:4,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [30]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [32]:
n[0].sum()

10

In [33]:
n[0].mean()

2.5

In [35]:
n.max()

20

In [36]:
n.min()

1

#### Pandas
- used for processing the data
- analysing the data
- two types(series,dataframe)
- Series(multiple row,single columns)(So only indexing is given)
- Dataframe(multiple row,multiple columns)(both columns and indexing are given)

In [51]:
#pip install pandas
import pandas as pd
s=pd.Series([1,2,3,4.5,'python','online','course'])
print(type(s))

<class 'pandas.core.series.Series'>


In [38]:
print(s)

0         1
1         2
2         3
3       4.5
4    python
5    online
6    course
dtype: object


In [39]:
s[0]

1

In [40]:
s.index

RangeIndex(start=0, stop=7, step=1)

In [41]:
dir(s)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__

### END

In [3]:
import pandas as pd
t=pd.Series(("gvpce","aditya","srkr","vignan","au","lendi","pydah")),index=["c1","c2","c3","c4","c5","c6","c7"]
t

SyntaxError: can't assign to function call (<ipython-input-3-6829eff12568>, line 2)

In [4]:
t.values

array(['gvpce', 'aditya', 'srkr', 'vignan', 'au', 'lendi', 'pydah'],
      dtype=object)

In [5]:
t.index

RangeIndex(start=0, stop=7, step=1)

In [6]:
t.values[0]

'gvpce'

In [7]:
t.values["c1"]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [10]:
s=pd.Series({"a":10,"b":20,"c":30}),index=['a','b','c']
s

SyntaxError: can't assign to function call (<ipython-input-10-3eac6ea88bef>, line 1)

#### Dataframe

In [14]:
df=pd.DataFrame([1,2,3,4])
df

0
0  1
1  2
2  3
3  4

In [15]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [17]:
df=pd.DataFrame([['math',75],['py',45],["m1",25],['m2',35]])
df

0   1
0  math  75
1    py  45
2    m1  25
3    m2  35

In [20]:
data=[['math',75],['py',45],["m1",25],['m2',35]]
df=pd.DataFrame(data,index=["sub1","sub2","sub3","sub4"],columns=["col1","col2"])
df

col1  col2
sub1  math    75
sub2    py    45
sub3    m1    25
sub4    m2    35

In [21]:
d=df.index
d[0]

'sub1'

### START

In [5]:
import pandas as pd
s=pd.Series(("gvpce","aditya","lendi","pydah","au","srkr"),index=['c1','c2','c3','c4','c5','c6'])
s

c1     gvpce
c2    aditya
c3     lendi
c4     pydah
c5        au
c6      srkr
dtype: object

In [6]:
s.index

Index(['c1', 'c2', 'c3', 'c4', 'c5', 'c6'], dtype='object')

In [8]:
s.values

array(['gvpce', 'aditya', 'lendi', 'pydah', 'au', 'srkr'], dtype=object)

In [9]:
s.values[0]

'gvpce'

In [10]:
s.values[0:3]

array(['gvpce', 'aditya', 'lendi'], dtype=object)

In [11]:
s.values[3::-2]

array(['pydah', 'aditya'], dtype=object)

In [12]:
s.values[-3::]

array(['pydah', 'au', 'srkr'], dtype=object)

In [13]:
s[0]

'gvpce'

In [14]:
s[0:3]

c1     gvpce
c2    aditya
c3     lendi
dtype: object

In [15]:
s[0:4]

c1     gvpce
c2    aditya
c3     lendi
c4     pydah
dtype: object

In [16]:
s[1:5]

c2    aditya
c3     lendi
c4     pydah
c5        au
dtype: object

In [17]:
s[0]="vasavi"

In [18]:
s    #------it is mutable

c1    vasavi
c2    aditya
c3     lendi
c4     pydah
c5        au
c6      srkr
dtype: object

In [19]:
import numpy as np
s=pd.Series(np.array([10,20,30,40]))
s

0    10
1    20
2    30
3    40
dtype: int32

In [21]:
s=pd.Series({"a":10,"b":20,"c":30})  #-------also can be given as dictionary
s

a    10
b    20
c    30
dtype: int64

In [22]:
s=pd.Series({"a":10,"b":20,"c":30},index=['a','b','c','d'])
s

a    10.0
b    20.0
c    30.0
d     NaN
dtype: float64

In [23]:
### as there is no value with index d it is returning NaN(not a number)

#### Dataframe

In [24]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [26]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [27]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [28]:
df=pd.DataFrame([1,2,3,4])
df

0
0  1
1  2
2  3
3  4

In [30]:
df=pd.DataFrame([['maths',75],['phy',45],['m1',35],['m2',40]])
df

0   1
0  maths  75
1    phy  45
2     m1  35
3     m2  40

In [32]:
data=[['maths',75],['phy',45],['m1',35],['m2',40]]
df=pd.DataFrame(data,index=['sub1','sub2','sub3','sub4'],columns=["col1","col2"])
df

col1  col2
sub1  maths    75
sub2    phy    45
sub3     m1    35
sub4     m2    40

In [33]:
df.index

Index(['sub1', 'sub2', 'sub3', 'sub4'], dtype='object')

In [34]:
df.columns

Index(['col1', 'col2'], dtype='object')

In [37]:
d=df.index
d

Index(['sub1', 'sub2', 'sub3', 'sub4'], dtype='object')

In [38]:
d[0]

'sub1'

In [39]:
df.values

array([['maths', 75],
       ['phy', 45],
       ['m1', 35],
       ['m2', 40]], dtype=object)

In [40]:
d1=df.values
d1

array([['maths', 75],
       ['phy', 45],
       ['m1', 35],
       ['m2', 40]], dtype=object)

In [41]:
d1[0]

array(['maths', 75], dtype=object)

In [42]:
d1[0][0]

'maths'

In [43]:
d1[0][1]

75

In [44]:
df=pd.DataFrame({'maths':[45,77,45,76],'phy':[40,90,80,70],'chem':[20,30,40,50]})
df

maths  phy  chem
0     45   40    20
1     77   90    30
2     45   80    40
3     76   70    50

In [46]:
data=({'maths':[45,77,45,76],'phy':[40,90,80,70],'chem':[20,30,40,50]})
df=pd.DataFrame(data,index=['a','b','c','d'])
df

maths  phy  chem
a     45   40    20
b     77   90    30
c     45   80    40
d     76   70    50

In [50]:
data=({'maths':pd.Series([45,56,67,78]),"phy":pd.Series([11,22,33,44]),"chem":pd.Series([10,20,30,40])})
df=pd.DataFrame(data,index=['a','b','c','d'])
df

maths  phy  chem
a    NaN  NaN   NaN
b    NaN  NaN   NaN
c    NaN  NaN   NaN
d    NaN  NaN   NaN

In [51]:
data=({'maths':pd.Series([45,56,67,78],index=['a','b','c','d']),"phy":pd.Series([11,22,33,44],index=['a','b','c','d']),"chem":pd.Series([10,20,30,40],index=['a','b','c','d'])})
df=pd.DataFrame(data,index=['a','b','c','d'])
df

maths  phy  chem
a     45   11    10
b     56   22    20
c     67   33    30
d     78   44    40

In [52]:
#To access data
df["maths"]  #----to access single column

a    45
b    56
c    67
d    78
Name: maths, dtype: int64

In [53]:
df['maths'][0]

45

In [54]:
df[0]

KeyError: 0

In [55]:
df['a']

KeyError: 'a'

In [57]:
# loc access only label names
df.loc['a']  #to access the single row

maths    45
phy      11
chem     10
Name: a, dtype: int64

In [59]:
df.loc[['a','d']]     #for multiple rows

maths  phy  chem
a     45   11    10
d     78   44    40

In [61]:
df[['maths','chem']]   #for multiple columns

maths  chem
a     45    10
b     56    20
c     67    30
d     78    40

In [62]:
#dof.loc[rows,columns]
df.loc[['a','c'],['maths','chem']]     # multiple rows and columns using loc

maths  chem
a     45    10
c     67    30

In [63]:
#   iloc---index location
#  it accepts position numbers
#  iloc[rows,columns]

In [64]:
df.iloc[[0,2],[0,2]]

maths  chem
a     45    10
c     67    30

In [69]:
df.iloc[0:3:2,0:3:2]    #----start:end:step

maths  chem
a     45    10
c     67    30

In [76]:
#last two columns using iloc
df.iloc[:,-2:]

phy  chem
a   11    10
b   22    20
c   33    30
d   44    40

In [77]:
df.iloc[::,1::]

phy  chem
a   11    10
b   22    20
c   33    30
d   44    40

In [79]:
df.iloc[0:5,1:3]

phy  chem
a   11    10
b   22    20
c   33    30
d   44    40

In [80]:
df["phy"][1]=100   #---to change values
df

maths  phy  chem
a     45   11    10
b     56  100    20
c     67   33    30
d     78   44    40